### PR TITLE
Added certLifetime and caLifetime setting and values

### PR DESCRIPTION
**Pull request by JonTheNiceGuy**
## Overview
This change will allow us to adjust the certificate lifespan for our internally hosted vault servers. Defaults persist at 10 years for the CA and 1 year for the certificate.

Upstreaming this patch will allow others to make this adjustment too.

There is no issue raised that is aligned to this PR.

## Notes for reviewer

We have used this "tweak" internally for some time, albeit with fixed values. I'm afraid I don't know how or where to add a test for this change, but am happy to build one/some if someone is willing to help me do it.

(Resubmit of #187 with correct committer/author values)

### CODE REVIEW

**Review by akijakya — CHANGES_REQUESTED** [review]
Hi @JonTheNiceGuy, thanks for the contribution! The helm chart linter caught an error:

```
Error:  templates/: template: vault-secrets-webhook/templates/webhook-deployment.yaml:37:28: executing "vault-secrets-webhook/templates/webhook-deployment.yaml" at <include (print $.Template.BasePath "/apiservice-webhook.yaml") .>: error calling include: template: vault-secrets-webhook/templates/apiservice-webhook.yaml:5:37: executing "vault-secrets-webhook/templates/apiservice-webhook.yaml" at <.Values.certificate.caLifespan>: wrong type for value; expected int; got float64
```

Please update the `apiservice-webhook` template to something like this:

```
... (.Values.certificate.caLifespan | int) ...
... (.Values.certificate.certLifespan | int) ...
```

If you could also test it again, that would be awesome, thanks! 🙂

**Comment by JonTheNiceGuy** [comment]
`helm lint .` now runs cleanly on mine (apologies, I forgot to run that). I'm waiting for my test cluster to come back up and then I'll deploy this.

**Review by JonTheNiceGuy — COMMENTED** [review]
Issues resolved in this commit

**Review by akijakya — APPROVED** [review]
LGTM, thanks!

**Comment by JonTheNiceGuy** [comment]
Just out of interest, do you know how long it'll be until this is turned into a release? :)

**Comment by akijakya** [comment]
I plan to do a release today!

**Comment by akijakya** [comment]
@JonTheNiceGuy sorry for the delay, a new version (v1.21.0) got released yesterday!

**Pull request merged**
